### PR TITLE
WIP: Implementing night mode

### PR DESCRIPTION
**Pull request by beeman**
Hey @hdjirdeh,

For a while I've been on the lookout for a HN client that has a nice night-mode. A few weeks ago I patched your project locally to get what I wanted, but after adding the Preferences screen to the app I thought it was time for a PR that implements it.

Please note, it's currently still WIP. Some of the things that need to be figured out:

#### How to define wether the app is in day/night mode. I thought about adding it as a class here: 
```html
<div id="wrapper" class="night">
```

#### How to the variables to the right one base on theme

If you look in `src/app/shared/_variables.scss` you'll see that I've created two sets of variables that map the values used in the components to the right theme color.

So `$wrapper-background-color` maps to `$theme-night-wrapper-background-color;`, but it really should do this based on which theme is selected. As I'm fairly new to using scss I'm not sure what would be the preferred way to implement this.

Some things that need to be done:

- [ ] Make sure every part of the interface is themed correctly in both themes
- [ ] Add the theme switcher to the Preferences screen
- [ ] Think about if we want to add more themes than just day/night. If so, are these names relevant or should it be light/dark?

⚠️ Please note, I've switched the project to `scss` mode by updating `angular-cli.json` and moving `src/style.css` to `src/style.scss`.

I hope you'll consider this feature, I'm looking forward to your feedback and working on getting it in there.

### CODE REVIEW

**Comment by hdjirdeh** [comment]
Wow thank you this is amazing! I agree this would be so awesome to have, and I think you're on the right path on setting it up without a doubt.

'<div id="wrapper" class="night">'

This makes perfect sense but a lot of the styles currently are still component specific, so i think we may need to conditionally add the theme class in the component levels as well as the wrapper parent. Once it's there, it's only a matter of different nested SCSS styles.

Will add a theme selector to the settings component today/tomorrow and start adding this in, thanks so much for this :)

**Comment by beeman** [comment]
I'm glad you like the idea 👍 

In terms of abstraction I think it would be good to keep the themes defined in 1 place and switch out the values of the variables based on the class on the top-level wrapper, but it looks like it's not that easy in SCSS. 

The big advantage of this approach is that adding a new theme can be done without touching any of the actual components, you just add it to the variables and the theme selector.

The more practical approach is probably apply theming to the individual components, as you suggested.

Happy to think some more on how to do this in a clean way.

**Comment by hdjirdeh** [comment]
Yeah I was thinking the exact same thing. It would be a a lot cleaner if we can just conditionally set the variables in that single place but doesn't look like that'll be too easy to do in SCSS :(

Will look into how we can do this in the easiest way however just to make things easier. Agreed it would make things a lot simpler if we don't dive into each component! Will let you know once I've thought of a possible way we can do this cleanly.

**Comment by hdjirdeh** [comment]
So wrapping a mixin seems to be a good way to do this I think. Adding a mixin to `_variables.scss` that includes all the classes in the app with `color` and `background-color` retrieved from set arguments. 

```
@mixin theme($name, $wrapper-background-color, $wrapper-color, $item-a-color) {
  .#{$name} {
    .wrapper {
      background-color: $wrapper-background-color;
      color: $wrapper-color;

      a {
        color: $item-a-color;
      }
    }
  }
}
```
This way we can just add new themes like so:

```
@include theme(
  default,
  $theme-day-wrapper-background-color,
  $theme-day-text-color,
  $theme-day-text-color
);

@include theme(
  night,
  $theme-night-wrapper-background-color,
  $theme-night-text-color,
  $theme-night-text-color
);
```

I think this is a pretty clean way to be honest, but let me know what you think. I just need to add the rest of classes that would have it's color/background-color change based on theme to the mixin, which I'll get to tomorrow 👍

**Comment by beeman** [comment]
That looks like a very good solution indeed! 👍

**Comment by hdjirdeh** [comment]
@beeman done!! Please take a look and let me know what you think, and let me know if you would prefer different colors than the ones I used

**Comment by beeman** [comment]
Awesome @hdjirdeh! Great work on the color scheme, very nice. 

Using the night mode makes a big difference when using it in dim light. I've started using this app as my daily driver for HN 👍

**Comment by hdjirdeh** [comment]
Agreed! Makes a big difference in dim light.

**Comment by hdjirdeh** [comment]
And glad to hear this app is your main avenue for Hacker News :)

**Pull request merged**
