### PR TITLE
Add types to API responses

### PR DESCRIPTION
**Pull request by zachberger**

### CODE REVIEW

**Comment by zachberger** [comment]
This is not quite ready to be merged. I'm looking for an example of the response when there is a poll. Once I have that out I'll update this PR.

**Comment by hdjirdeh** [comment]
Thanks a million for this! [Here's](https://angular2-hn.firebaseapp.com/item/7059569) an example of a poll. The item response has a poll object that looks like this:

image

For some reason, the API only returns the poll results, so we trigger more requests to get the actual poll content. For example, if the item id === 1 and has 2 poll choices, then the contents of each poll choice can be retrieved from `/2` and `/3`. (All this is done [here](https://github.com/hdjirdeh/angular2-hn/blob/master/src/app/item-comments/item-comments.component.ts#L31-L38))

**Comment by zachberger** [comment]
I've added typing for the polls. As the commit mentions I moved the poll result fetching into the HN API Service. In general controllers should be unconcerned about how the API works. By moving fetching poll details into the service we maintain this separation of concerns.

**Comment by hdjirdeh** [comment]
Agreed, poll fetching shouldn't have been in the controller in the first place.

Genuinely can't thank you enough for this! This is amazing :)

**Pull request merged**
